<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('196', '/uploads/allimg/180307/1-1P30G00103I5.jpg');
$maNum = 1;
$myaddons[$maNum] = array('197', '/uploads/allimg/180307/1-1P30G0055c21.png');
$maNum = 2;
$myaddons[$maNum] = array('198', '/uploads/allimg/180307/1-1P30G01S3J0.png');
$maNum = 3;
$myaddons[$maNum] = array('199', '/uploads/allimg/180307/1-1P30G019105b.png');
$maNum = 4;
$myaddons[$maNum] = array('200', '/uploads/allimg/180307/1-1P30G02432A1.jpg');
$maNum = 5;
$myaddons[$maNum] = array('201', '/uploads/allimg/180307/1-1P30G05R2516.png');
$maNum = 6;
$myaddons[$maNum] = array('202', '/uploads/allimg/180307/1-1P30G115332O.jpg');
$maNum = 7;
