<li id="projectitem_[field:global name=autoindex runphp=" yes "]@me=@me-1;[/field:global]" class="projectitem wow" style="width: 350px; height: 300px;">
												<a href="[field:arcurl/]" class="projectitem_content">
													<div class="projectitem_wrapper">
														<div class="project_img">
															<img src="[field:litpic/]" width="650" height="385" />
														</div>
														<div class="project_info">
															<div style="height:50px;">
																<p class="title" style="height: 50px; line-height: 50px; padding: 0 0 0 20px;">[field:title/]</p>
															</div>
														</div>
													</div>
												</a>
											</li>