<li id="projectitem_[field:global name=autoindex runphp=" yes "]@me=@me-1;[/field:global]" class="projectitem wow">
												<a href="[field:arcurl/]" class="projectitem_content">
													<div class="projectitem_wrapper">
														<div class="project_img">
															<img src="[field:litpic/]" width="650" height="385" />
														</div>
														<div class="project_info">
															<div>
																<p class="title">[field:title/]</p>
															</div>
														</div>
													</div>
												</a>
											</li>