<li style="background-image:url([field:litpic/])" class="active">
          <div id="tempImage_1"></div>
          <video width="100%" height="100%" autoplay="" loop="" preload="auto" class="slider-video" style="width:100%; height:auto;">
            <source src="" type="video/mp4"></source>
          </video>
          <div class="mask"></div>
          <a target="_blank">
          <div>
            <p class="title ellipsis"></p>
          </div>
          <div class="sliderArrow fa fa-angle-down"></div>
          </a></li>