<?php
$z[0]=Array("id","",80,91);
$z[0][4]=array();
$z[1]=Array("litpic","",141,156);
$z[1][4]=array();
$z[2]=Array("pubdate","",260,309);
$z[2][4]=array();
$z[2][4]['function']="strftime(\"%m-%d\",@me)";
$z[3]=Array("pubdate","",345,391);
$z[3][4]=array();
$z[3][4]['function']="strftime(\"%Y\",@me)";
$z[4]=Array("title","",493,507);
$z[4][4]=array();
$z[5]=Array("description","",550,600);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,250)";

?>