
<field:xm itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xm>

<field:xl itemname="学历" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xl>

<field:dh itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dh>

<field:wx itemname="微信" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:wx>
