<div class="newstitem plr10 wow fadeIn" data-wow-delay="0.[field:global name=autoindex runphp="yes"]@me=@me-1;[/field:global]s"> <a class="newsinfo" href="view.php?aid=17">
              <div class="newsimage"> <img src="[field:litpic/]" width="auto" height="auto" /> </div>
              <div class="newsdate">
                <p class="md">[field:pubdate function='strftime("%m-%d",@me)'/]</p>
                <p class="year">[field:pubdate function='strftime("%Y",@me)'/]</p>
              </div>
              <div class="newsbody">
                <p class="title ellipsis">[field:title/]</p>
                <p class="description">[field:description function='cn_substr(@me,150)'/]...</p>
              </div>
              </a> </div>