<ul class="content_list" data-options-sliders="8" data-options-margin="15" data-options-ease="1" data-options-speed="1"  style="margin-top:90px;">
											
											<li id="projectitem_[field:global name=autoindex runphp=" yes "]@me=@me-1;[/field:global]" class="projectitem wow">
												<a href="[field:arcurl/]" class="projectitem_content">
													<div class="projectitem_wrapper">
														<div class="project_img">
															<img src="[field:litpic/]" width="650" height="385" />
														</div>
														<div class="project_info">
															<div>
																<p class="title">[field:title/]</p>
															</div>
														</div>
													</div>
												</a>
												
											</li>
											<!--<li id="projectitem_[field:global name=autoindex runphp=" yes "]@me=@me-1;[/field:global]" class="projectitem wow">
												<a href="./a/keshi/k2/" class="projectitem_content">
													<div class="projectitem_wrapper">
														<div class="project_img">
															<img src="/style/images/shengzi.jpg" width="650" height="385" />
														</div>
														<div class="project_info">
															<div>
																<p class="title">赴美生子</p>
															</div>
														</div>
													</div>
												</a>
											</li>
											<li id="projectitem_[field:global name=autoindex runphp=" yes "]@me=@me-1;[/field:global]" class="projectitem wow">
											<a href="./a/keshi/k3/" class="projectitem_content">
											<div class="projectitem_wrapper">
											<div class="project_img">
											<img src="/style/images/jiuyi.jpg" width="650" height="385" /></div>
											<div class="project_info">
											<div>
											<p class="title">赴美就医</p></div>
											</div>
											</div>
											</a>
											</li>
											<li id="projectitem_[field:global name=autoindex runphp=" yes "]@me=@me-1;[/field:global]" class="projectitem wow">
											<a href="./a/keshi/k4/" class="projectitem_content">
											<div class="projectitem_wrapper">
											<div class="project_img">
											<img src="/style/images/jinxiu.jpg" width="650" height="385" /></div>
											<div class="project_info">
											<div>
											<p class="title">赴美进修</p></div>
											</div>
											</div>
											</a>
											</li>
											
											
											<li id="projectitem_[field:global name=autoindex runphp=" yes "]@me=@me-1;[/field:global]" class="projectitem wow">
												<a href="./a/keshi/k1/" class="projectitem_content">
													<div class="projectitem_wrapper">
														<div class="project_img">
															<img src="/style/images/yuancheng.jpg" width="650" height="385" />
														</div>
														<div class="project_info">
															<div>
																<p class="title">远程诊疗</p>
															</div>
														</div>
													</div>
												</a>
											</li>
											<li id="projectitem_[field:global name=autoindex runphp=" yes "]@me=@me-1;[/field:global]" class="projectitem wow">
												<a href="./a/keshi/k2/" class="projectitem_content">
													<div class="projectitem_wrapper">
														<div class="project_img">
															<img src="/style/images/shengzi.jpg" width="650" height="385" />
														</div>
														<div class="project_info">
															<div>
																<p class="title">赴美生子</p>
															</div>
														</div>
													</div>
												</a>
											</li>
											<li id="projectitem_[field:global name=autoindex runphp=" yes "]@me=@me-1;[/field:global]" class="projectitem wow">
											<a href="./a/keshi/k3/" class="projectitem_content">
											<div class="projectitem_wrapper">
											<div class="project_img">
											<img src="/style/images/jiuyi.jpg" width="650" height="385" /></div>
											<div class="project_info">
											<div>
											<p class="title">赴美就医</p></div>
											</div>
											</div>
											</a>
											</li>
											<li id="projectitem_[field:global name=autoindex runphp=" yes "]@me=@me-1;[/field:global]" class="projectitem wow">
											<a href="./a/keshi/k4/" class="projectitem_content">
											<div class="projectitem_wrapper">
											<div class="project_img">
											<img src="/style/images/jinxiu.jpg" width="650" height="385" /></div>
											<div class="project_info">
											<div>
											<p class="title">赴美进修</p></div>
											</div>
											</div>
											</a>
											</li>-->
										</ul>