
<field:xm itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xm>

<field:xl itemname="学历" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xl>

<field:dh itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dh>

<field:wx itemname="微信" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:wx>

<field:qq itemname="QQ" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:qq>

<field:yx itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:yx>

<field:dz itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dz>

<field:jb itemname="疾病" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:jb>

<field:bz itemname="备注" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:bz>
