<li id="teamitem_[field:global name=autoindex runphp="yes"]@me=@me;[/field:global]" class="wow">
                <div class="header wow" data-wow-delay=".4s"> <a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" width="180" height="180" /></a> </div>
                <div class="summary wow">
                  <p class="title"><a href="[field:arcurl/]">[field:title/]</a></p>
                  <p class="subtitle">[field:weizhi/]</p>
                  <p class="description wow">[field:description function='cn_substr(@me,150)'/]...</p>
                </div>
                <a href="[field:arcurl/]" target="_blank" class="details">more<i class="fa fa-angle-right"></i></a> </li>