<?php
$z[0]=Array("arcurl","",32,47);
$z[0][4]=array();
$z[1]=Array("litpic","",59,74);
$z[1][4]=array();
$z[2]=Array("arcurl","",327,342);
$z[2][4]=array();
$z[3]=Array("title","",344,358);
$z[3][4]=array();
$z[4]=Array("weizhi","",402,417);
$z[4][4]=array();
$z[5]=Array("description","",460,510);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,250)";
$z[6]=Array("arcurl","",561,576);
$z[6][4]=array();

?>