<li id="projectitem_[field:global name=autoindex runphp=" yes "]@me=@me-1;[/field:global]" class="projectitem wow" style="width: 300px; height: 280px;">
												<a href="[field:arcurl/]" class="projectitem_content">
													<div class="projectitem_wrapper">
														<div class="project_img">
															<img src="[field:litpic/]"style="height: 250px;"/>
														</div>
														<div class="project_info">
															<div style="height:50px;">
																<p class="title" style="height: 30px; line-height: 30px; padding: 0 0 0 20px;">[field:title/]</p>
															</div>
														</div>
													</div>
												</a>
											</li>