<li> <a href="[field:arcurl/]" target="_blank">
            <div class="img"> <img style="height: auto; border-radius: 3px; width: 100%; height: 200px;" src="[field:litpic/]"> 
            	<div style="position: absolute;top: 0; left: 0; right: 0; bottom: 0; text-align: center;">
			<div class="img" style="margin-top: 160px; font-size: 18px; font-weight: bold; color: white; width: 100%; height: 50px; opacity: 0.6; background: black; line-height: 30px;">[field:title /]</div>
              <table>
                <tbody>
                  <tr>
                    <td></td>
                  </tr>
                </tbody>
              </table>
            </div>
            </div>
            
           </a> 
          </li>