<div id="newsitem_1" class="wow newstitem left"> <a class="newscontent" target="_blank" href="[field:arcurl/]">
            <div class="news_wrapper">
              <div class="newsbody">
                <p class="date"><span class="md">2016<span>-</span></span><span class="year">12-01</span></p>
                <p class="title">[field:title/]</p>
                <div class="separator"></div>
                <p class="description">[field:description function='cn_substr(@me,250)'/]...</p>
              </div>
            </div>
            <div class="newsimg" style="background-image:url([field:litpic/])"></div>
            </a> <a href="[field:arcurl/]" target="_blank" class="details">more<i class="fa fa-angle-right"></i></a> </div>