<div class="projectitem wow fadeIn"> <a href="view.php?aid=[field:id/]">
              <div class="project_img"> <img src="[field:litpic/]" width="500" height="320" /> </div>
              <div class="project_info">
                <div>
                  <p class="title">[field:title/]</p>
                  <p class="description">[field:description function='cn_substr(@me,50)'/]...</p>
                </div>
              </div>
              </a> </div>