<li id="projectitem_1" class="projectitem wow"> <a href="view.php?aid=[field:id/]" class="projectitem_content" target="_blank">
                      <div class="projectitem_wrapper">
                        <div class="project_img"> <img src="[field:litpic/]" width="650" height="385" /> </div>
                        <div class="project_info">
                          <div>
                            <p class="title">[field:title/]</p>
                            <p class="subtitle"></p>
                            <p class="description hide">[field:description function='cn_substr(@me,150)'/]...</p>
                          </div>
                        </div>
                      </div>
                      </a> </li>