<?php
$z[0]=Array("global","@me=@me-1;",20,89);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",136,151);
$z[1][4]=array();
$z[2]=Array("litpic","",192,207);
$z[2][4]=array();
$z[3]=Array("title","",273,287);
$z[3][4]=array();
$z[4]=Array("description","",328,377);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,50)";
$z[5]=Array("arcurl","",440,455);
$z[5][4]=array();

?>