<?php
$z[0]=Array("field","",381,400);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",401,427);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",468,490);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",530,581);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1533,1570);
$z[4][4]=array();
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("field","",1814,1836);
$z[5][4]=array();
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n            <li><a href='list.php?tid=[field:id/]'>[field:typename/]</a></li>\r\n            ",1949,2157);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='active'>~typename~</a></li>";
$z[7]=Array("field","",2320,2342);
$z[7][4]=array();
$z[7][4]['name']="typename";
$z[8]=Array("include","",8463,8500);
$z[8][4]=array();
$z[8][4]['filename']="foot_m.htm";
$z[9]=Array("include","",8572,8608);
$z[9][4]=array();
$z[9][4]['filename']="nav_m.htm";

?>