<?php
$z[0]=Array("field","",379,398);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",399,425);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",466,495);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",535,593);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1008,1045);
$z[4][4]=array();
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("list","\r\n            <li class=\"serviceitem wow fadeIn\"><a href=\"view.php?aid=[field:id/]\"><img src=\"[field:litpic/]\" width=\"320\" height=\"120\" /></a>\r\n              <div>\r\n                <p class=\"title ellipsis\">[field:title/]</p>\r\n                <p class=\"description\">[field:description function='cn_substr(@me,100)'/]...</p>\r\n              </div>\r\n            </li>\r\n            <li class=\"line\"></li>\r\n            ",1212,1663);
$z[5][4]=array();
$z[5][4]['titlelen']="60";
$z[6]=Array("include","",1773,1810);
$z[6][4]=array();
$z[6][4]['filename']="foot_m.htm";
$z[7]=Array("include","",1878,1914);
$z[7][4]=array();
$z[7][4]['filename']="nav_m.htm";

?>